server:
  port: 8081

spring:
  application:
    name: cr-user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudfuck
    username: cloud
    password: logic
  jpa:
    hibernate:
      ddl-auto: none  # Changed from update to validate since Flyway will handle schema updates
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    validate-on-migrate: false  # Change this to false
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.flywaydb: DEBUG  # Added to see Flyway migration details

dunkware:
  security:
    permitAll:
      - /users/validate