server:
  port: 8025

spring:
  config:
    import=optional:configserver:
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:454564/eureka/
dunkware:
  security:
    permitAll:
      - /login
      - /validate
      - /register

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler: TRACE
    org.springframework.cloud.gateway.filter: TRACE
    org.springframework.cloud.gateway.route: TRACE
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    org.springframework.cloud.gateway.filter.GlobalFilter: TRACE