apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.credentials.postgres_password | b64enc }}
